//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gardener.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gardener.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на сдачу в аренду помещения.
        /// </summary>
        internal static string Applicationforleaseofinpremises {
            get {
                return ResourceManager.GetString("Applicationforleaseofinpremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на аренду помещения.
        /// </summary>
        internal static string Applicationforleaseofpremises {
            get {
                return ResourceManager.GetString("Applicationforleaseofpremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма заявки на аренду помещения.
        /// </summary>
        internal static string Applicationformforleaseofinpremises {
            get {
                return ResourceManager.GetString("Applicationformforleaseofinpremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма заявки на сдачу в аренду помещения.
        /// </summary>
        internal static string Applicationformforleaseofpremises {
            get {
                return ResourceManager.GetString("Applicationformforleaseofpremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызов охраны.
        /// </summary>
        internal static string CallSecurity {
            get {
                return ResourceManager.GetString("CallSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ковры и текстиль.
        /// </summary>
        internal static string Carpetsandtextiles {
            get {
                return ResourceManager.GetString("Carpetsandtextiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вещевые ряды.
        /// </summary>
        internal static string Clothingseries {
            get {
                return ResourceManager.GetString("Clothingseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пальтовый круг.
        /// </summary>
        internal static string Coatcircle {
            get {
                return ResourceManager.GetString("Coatcircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Котировки валют.
        /// </summary>
        internal static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы валют ЦБ РФ.
        /// </summary>
        internal static string CoursesTableTitle {
            get {
                return ResourceManager.GetString("CoursesTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызов врача.
        /// </summary>
        internal static string EmployCall {
            get {
                return ResourceManager.GetString("EmployCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка отправки формы.
        /// </summary>
        internal static string Errorsubmittingform {
            get {
                return ResourceManager.GetString("Errorsubmittingform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободные места.
        /// </summary>
        internal static string FreePlace {
            get {
                return ResourceManager.GetString("FreePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меха и кожа.
        /// </summary>
        internal static string Furandleather {
            get {
                return ResourceManager.GetString("Furandleather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список свободных помещений.
        /// </summary>
        internal static string Listofavailablepremises {
            get {
                return ResourceManager.GetString("Listofavailablepremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор действия.
        /// </summary>
        internal static string ListSalePageTitle {
            get {
                return ResourceManager.GetString("ListSalePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема рынка.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости рынка.
        /// </summary>
        internal static string Marketnews {
            get {
                return ResourceManager.GetString("Marketnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        internal static string RatesTitle {
            get {
                return ResourceManager.GetString("RatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аренда торговых помещений.
        /// </summary>
        internal static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список свободных помещений.
        /// </summary>
        internal static string RentSalePageTitle {
            get {
                return ResourceManager.GetString("RentSalePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ряд.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызов мастера (Лайон).
        /// </summary>
        internal static string Selling {
            get {
                return ResourceManager.GetString("Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить заявку.
        /// </summary>
        internal static string SendButtonText {
            get {
                return ResourceManager.GetString("SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма успешно отправлена.
        /// </summary>
        internal static string Theformwassuccessfullysent {
            get {
                return ResourceManager.GetString("Theformwassuccessfullysent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый ТЦ.
        /// </summary>
        internal static string Thenewshoppingcenter {
            get {
                return ResourceManager.GetString("Thenewshoppingcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТЦ Садовод.
        /// </summary>
        internal static string Ttsgreenthumb {
            get {
                return ResourceManager.GetString("Ttsgreenthumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание сети.
        /// </summary>
        internal static string WaitingForNetwork {
            get {
                return ResourceManager.GetString("WaitingForNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свадебная галерея &apos;САЛЮТ&apos;.
        /// </summary>
        internal static string Weddinggallery {
            get {
                return ResourceManager.GetString("Weddinggallery", resourceCulture);
            }
        }
    }
}
