//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gardener.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gardener.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка на сдачу в аренду помещения.
        /// </summary>
        internal static string Applicationforleaseofinpremises {
            get {
                return ResourceManager.GetString("Applicationforleaseofinpremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка на аренду помещения.
        /// </summary>
        internal static string Applicationforleaseofpremises {
            get {
                return ResourceManager.GetString("Applicationforleaseofpremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма заявки на сдачу в аренду помещения.
        /// </summary>
        internal static string Applicationformforleaseofpremises {
            get {
                return ResourceManager.GetString("Applicationformforleaseofpremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызов охраны.
        /// </summary>
        internal static string CallSecurity {
            get {
                return ResourceManager.GetString("CallSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ковры и текстиль.
        /// </summary>
        internal static string Carpetsandtextiles {
            get {
                return ResourceManager.GetString("Carpetsandtextiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вещевые ряды.
        /// </summary>
        internal static string Clothingseries {
            get {
                return ResourceManager.GetString("Clothingseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пальтовый круг.
        /// </summary>
        internal static string Coatcircle {
            get {
                return ResourceManager.GetString("Coatcircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Котировки валют.
        /// </summary>
        internal static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курсы валют ЦБ РФ.
        /// </summary>
        internal static string CoursesTableTitle {
            get {
                return ResourceManager.GetString("CoursesTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызов врача.
        /// </summary>
        internal static string EmployCall {
            get {
                return ResourceManager.GetString("EmployCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка отправки формы.
        /// </summary>
        internal static string Errorsubmittingform {
            get {
                return ResourceManager.GetString("Errorsubmittingform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меха и кожа.
        /// </summary>
        internal static string Furandleather {
            get {
                return ResourceManager.GetString("Furandleather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список свободных помещений.
        /// </summary>
        internal static string Listofavailablepremises {
            get {
                return ResourceManager.GetString("Listofavailablepremises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема рынка.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости рынка.
        /// </summary>
        internal static string Marketnews {
            get {
                return ResourceManager.GetString("Marketnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта.
        /// </summary>
        internal static string RatesTitle {
            get {
                return ResourceManager.GetString("RatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аренда торговых помещений.
        /// </summary>
        internal static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список свободных помещений.
        /// </summary>
        internal static string RentSalePageTitle {
            get {
                return ResourceManager.GetString("RentSalePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызов мастера (Лайон).
        /// </summary>
        internal static string Selling {
            get {
                return ResourceManager.GetString("Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма успешно отправлена.
        /// </summary>
        internal static string Theformwassuccessfullysent {
            get {
                return ResourceManager.GetString("Theformwassuccessfullysent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый ТЦ.
        /// </summary>
        internal static string Thenewshoppingcenter {
            get {
                return ResourceManager.GetString("Thenewshoppingcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТЦ Садовод.
        /// </summary>
        internal static string Ttsgreenthumb {
            get {
                return ResourceManager.GetString("Ttsgreenthumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свадебная галерея &apos;САЛЮТ&apos;.
        /// </summary>
        internal static string Weddinggallery {
            get {
                return ResourceManager.GetString("Weddinggallery", resourceCulture);
            }
        }
    }
}
